name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#    - name: Free Disk Space (Ubuntu)
#      uses: jlumbroso/free-disk-space@main
#      with:
#        # this might remove tools that are actually needed,
#        # if set to "true" but frees about 6 GB
#        tool-cache: false
#        # all of these default to true, but feel free to set to
#        # "false" if necessary for your workflow
#        android: true
#        dotnet: true
#        haskell: true
#        large-packages: true
#        docker-images: true
#        swap-storage: true
    - uses: actions/checkout@v4
      name: Check out code
    - name: Test1
      id: t1
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "yyyy-MM-dd"

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: yaming116/sherpa-onnx-asr
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
        tags: zipformer-${{ steps.t1.outputs.year }}-${{ steps.t1.outputs.month }}-${{ steps.t1.outputs.day }}
        registry: docker.io
        dockerfile: Dockerfile
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: yaming116/sherpa-onnx-asr
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
        tags: paraformer-${{ steps.t1.outputs.year }}-${{ steps.t1.outputs.month }}-${{ steps.t1.outputs.day }}
        registry: docker.io
        dockerfile: Dockerfile
        buildArgs: "MODEL=paraformer,DELETE_NAMES='model.onnx',MODEL_FILE_NAME='sherpa-onnx-paraformer-zh-2023-03-28.tar.bz2'"
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}



  
